app_name: ed
image_name: ed-image
location: us-central1
nonprod:
    tag: $(location)-docker.pkg.dev/collegis-shared-services-dev/repo-collegis-shared-services-dev/$(image_name):latest
prod:
    tag: $(location)-docker.pkg.dev/collegis-shared-services-prod/repo-collegis-shared-services-prod/$(image_name):latest